CREATE DATABASE IF NOT EXISTS `db_absen_jumat`;
USE `db_absen_jumat`;

CREATE TABLE IF NOT EXISTS `users` (
    id INT AUTO_INCREMENT PRIMARY KEY,
    level INTEGER(1),
    rayon VARCHAR(20),
    nama VARCHAR(50),
    password VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS `siswa` (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nama VARCHAR(200),
    nis  INTEGER(8),
    rayon VARCHAR(50),
    rombel VARCHAR(50),
    status ENUM('Hadir', 'Tidak Hadir') DEFAULT 'Hadir'
);

CREATE TABLE IF NOT EXISTS `rekap` (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nama VARCHAR(200),
    nis  INTEGER(8),
    rayon VARCHAR(50),
    rombel VARCHAR(50),
    status VARCHAR(20),
    tanggal DATE
);

INSERT INTO `siswa` (nama,nis, rayon,rombel) VALUES ('Azhar Muzakki', 12309555,'Wik-1', 'TJKT-X-3'),
                                                    ('Molldy Apriansyah', 12309555,'Wik-1', 'DKV-X-2'),
                                                    ('Syahrur Ramadhan', 12310084,'Wik-1', 'TJKT-X-1'),
                                                    ('Ramadhan Alfajrie', 12209363,'Wik-1', 'PPLG-XI-4'),
                                                    ('Muhamad Bahrul Widad Sauqi', 12209154,'Wik-1', 'TJKT-XI-2'),
                                                    ('Muhamad Muslih', 12209180,'Wik-1', 'TJKT-XI-2'),
                                                    ('Rayandra Abyakta Tjondro Andoyo', 12209373,'Wik-1', 'PMN-XI-2'),
                                                    ('Muhamad Bintang Ramadhani', 12209157,'Wik-1', 'DKV-XI-1'),
                                                    ('Muhammad Aryo Wibisono', 12209208,'Wik-1', 'DKV-XI-1'),
                                                    ('Luqman Halim Baraba', 12209096,'Wik-1', 'DKV-XI-2'),
                                                    ('Gama Husen', 12209021,'Wik-1', 'PPLG-XI-3'),
                                                    ('Arfan Hashif Hairuman', 12208911,'Wik-1', 'PPLG-XI-4'),
                                                    ('Gandang Arvin Hakim', 12209022,'Wik-1', 'PPLG-XI-4'),
                                                    ('Fikri Taufik Rahman', 12108854,'Wik-1', 'PMN-XII-2'),
                                                    ('Muhammad Rashid Syafithra', 12108617,'Wik-1', 'DKV-XII-1'),
                                                    ('Muhamad Ridho Alfauzan', 12108562,'Wik-1', 'DKV-XII-2'),
                                                    ('Rafael Ramadhan', 12108692,'Wik-1', 'DKV-XII-2'),
                                                    ('Muhammad Kika Haekal', 12108600,'Wik-1', 'PPLG-XII-1'),
                                                    ('Abimanyu Satria Megantara', 12108269,'Wik-1', 'PPLG-XII-2'),
                                                    ('Akmal Maulana Basri', 12108292,'Wik-1', 'PPLG-XII-2'),
                                                    ('Dzaka Alif Nurhakim', 12108397,'Wik-1', 'PPLG-XII-2'),
                                                    ('Adrian Fathir Firmansyah', 12108279,'Wik-1', 'PPLG-XII-3'),
                                                    ('Muhamad Ihsan Rasyidin', 12108555,'Wik-1', 'PPLG-XII-5'),
                                                    ('Azhar Daffansyah', 12108344,'Wik-1', 'TJKT-XII-1'),
                                                    ('Raihan Ramadhan', 12108702,'Wik-1', 'TJKT-XII-2'),
                                                    ('Evan Fathoni Ramadhan', 12108411,'Wik-1', 'TJKT-XII-5'),
                                                    ('M. Samirafi Pasha', 12108498,'Wik-1', 'TJKT-XII-4'),
                                                    ('Dzaki Chrisna Nurhakim', 12108398,'Wik-1', 'KLN-XII-1'),
                                                    ('Mochamad Fahrezqi Qolbinoor', 12309744,'Wik-2', 'TJKT-X-2'),
                                                    ('Qavi Zainal Mustofa', 12309963,'Wik-2', 'PPLG-X-1'),
                                                    ('Muhamad Zidan', 12309816,'Wik-2', 'DKV-X-2'),
                                                    ('Simon', 12209416,'Wik-2', 'PPLG-XI-5'),
                                                    ('Hafiz Al Rifqi', 12209033,'Wik-2', 'PPLG-XI-6'),
                                                    ('Asyaam Amanullah', 12208923,'Wik-2', 'TJKT-XI-1'),
                                                    ('Gathan Al Ghaniyyu Sujudi', 12209024,'Wik-2', 'TJKT-XI-1'),
                                                    ('Muhammad Luthfi Ramadhani', 12209248,'Wik-2', 'TJKT-XI-3'),
                                                    ('Muhammad Zaki Rizqullah', 12209285,'Wik-2', 'DKV-XI-1'),
                                                    ('Zaki Adhitia', 12209473,'Wik-2', 'PPLG-XI-2'),
                                                    ('Muhammad Ikhsan Faadhil', 12209239,'Wik-2', 'PPLG-XI-5'),
                                                    ('Arizona K Sidi', 12108853,'Wik-2', 'HTL-XII-1'),
                                                    ('Fathir Mochammad Delpieryan Rachman', 12108420,'Wik-2', 'DKV-XII-1'),
                                                    ('Moch Alfahsyadz Syarif', 12108519,'Wik-2', 'DKV-XII-1'),
                                                    ('Mohamad Iksan Faturrohman', 12108528,'Wik-2', 'DKV-XII-1'),
                                                    ('Nayaka Moh Nabiel Chaer', 12108655,'Wik-2', 'DKV-XII-2'),
                                                    ('Rafi Achmad Farabi', 12108694,'Wik-2', 'TJKT-XII-1'),
                                                    ('Galang Putra Pratama', 12108438,'Wik-2', 'TJKT-XII-2'),
                                                    ('Adriano Rizki Ramadhan', 12108281,'Wik-2', 'TJKT-XII-3'),
                                                    ('M.Ariono Putra Agusni', 12108502,'Wik-2', 'TJKT-XII-3'),
                                                    ('Noer Muhamad Aril Apriliansyah', 12309947,'Wik-3', 'DKV-X-3'),
                                                    ('Muhamad Rifa Aldimas', 12309802,'Wik-3', 'PPLG-X-2'),
                                                    ('Abiyu Rafi Linta Aribawa', 12208862,'Wik-3', 'PPLG-XI-6'),
                                                    ('Aufa As ad Atsal Fikri Sophianto', 12208927,'Wik-3', 'PPLG-XI-6'),
                                                    ('Arya Nandika Riptohadi', 12208918,'Wik-3', 'TJKT-XI-1'),
                                                    ('Muhamad Tsaqeef Zimraan Pua Upa', 12209199,'Wik-3', 'TJKT-XI-1'),
                                                    ('Ahmad Harun Ar Rasyid', 12208875,'Wik-3', 'TJKT-XI-3'),
                                                    ('Rassya Dhafa Al Rizqi', 12209369,'Wik-3', 'TJKT-XI-3'),
                                                    ('Malik Abdul Jabbar Rambe', 12209121,'Wik-3', 'DKV-XI-I'),
                                                    ('Muhammad Rizky Pramudhita Hanggara', 12209272,'Wik-3', 'DKV-XI-I'),
                                                    ('Nizar Muzakki Abdillah', 12209323,'Wik-3', 'DKV-XI-2'),
                                                    ('Muhamad Gigih Aliandanu Sukma', 12209172,'Wik-3', 'DKV-XI-3'),
                                                    ('Sigit Putra Pratama', 12209415,'Wik-3', 'PPLG-XI-2'),
                                                    ('Sultan Faid Amani', 12209444,'Wik-3', 'PPLG-XI-2'),
                                                    ('Ahmad Hafidz Rino Putra', 12208874,'Wik-3', 'PPLG-XI-5'),
                                                    ('Aria Manggala Putra', 12208913,'Wik-3', 'PPLG-XI-5'),
                                                    ('Muhammad Rizky Dwiansyah', 12209270,'Wik-3', 'PPLG-XI-5'),
                                                    ('Dede Ridwan Salim Syuhada', 12108377,'Wik-3', 'TJKT-XII-4'),
                                                    ('Muhammad Dzikry Firdaus', 12108578,'Wik-3', 'TJKT-XII-4'),
                                                    ('Raden Alif Taufiqulhakim', 12108687,'Wik-3', 'TJKT-XII-4'),
                                                    ('Mohammad Kautsar Zanjabil', 12108530,'Wik-3', 'KLN-XII-1'),
                                                    ('Muhammad Farel Alhafidz Sulaeman', 12108585,'Wik-3', 'DKV-XII-1'),
                                                    ('Arief Abdurahman', 12108331,'Wik-3', 'DKV-XII-2'),
                                                    ('Muhammad Naufal Asadel Fathi', 12108604,'Wik-3', 'DKV-XII-2'),
                                                    ('Aufa Putera Badillah', 12108336,'Wik-3', 'PPLG-XII-5');

INSERT INTO `users` (level,rayon,nama,password) VALUES (1, 'Wik-3', 'Atjep', 'Wikrama123'),
                                                       (1, 'Wik-1', 'Nunuk', 'Wikrama123'),
                                                       (1, 'Wik-2', 'Budiono', 'Wikrama123'),
                                                       (2, 'Wik-1', 'Yoga', 'Wikrama123'),
                                                       (2, 'Wik-2', 'Yogi', 'Wikrama123'),
                                                       (2, 'Wik-3', 'Putra', 'Wikrama123'),
                                                       (3, 'Kesis', 'Komalasari', 'Wikrama123'),
                                                       (3, 'Kesis', 'Ridwan', 'Wikrama123');